### ISSUE TITLE
signer is assumed

### ISSUE THREAD

**Issue by RezaTheGreat** [ensdomains/ensjs-v3#12]
Hi there. i reviewed with library that found out that the provider is assumed to be holding the private keys. e.g metamask. however this makes it unusable in node with providers that don't hold the private keys like infura, alchemy, etc. since they don't hold private keys they don't allow the `eth_sendTransaction` method. I think it would be nice to either get the signer for instantiating the contracts when in the constructor so a signer with a private key can be handed as well. this way the contract methods can be used with the aforementioned providers as well. heres a working piece of code with those things considered. 

it's using the ensjs v2 but they work the same in this criteria
```
async function setSubnodeRecordExample() {
  const provider = new ethers.providers.JsonRpcProvider(INFURA_PROVIDER_URL);
  // const provider = providers.getDefaultProvider('mainnet');

  const signer = new ethers.Wallet(privateKey, provider);
  const ensContract = new ethers.Contract('registry.ens.eth', ensAbi.abi, signer);

  const ens = new ENS({ provider, ensAddress: getEnsAddress('1') });

  const nameWrapper = ens.name('nameWrapper.eth');
  const onwer = await nameWrapper.getOwner();

  const resolver = await nameWrapper.getResolver();

  const lh = labelhash('test');
  const nh = namehash('nameWrapper.eth');

  const Submitedtransaction = await ensContract.estimateGas.setSubnodeRecord(nh, lh, onwer, resolver, 100000);

  console.log(Submitedtransaction);
}
```
this way the contract is instantiated using the signer from the private key and does the job.
I'd like to hear from you guys about this.

**Comment by TateB** [comment]
fixed in v3.0.0-alpha.5
