### ISSUE TITLE
Error TS2526: A 'this' type is available only in a non-static member of a class or interface

### ISSUE THREAD

**Issue by sherpya** [ensdomains/ensjs-v3#149]
```
node_modules/@ensdomains/ensjs/dist/types/index.d.ts:604:159 - error TS2526: A 'this' type is available only in a non-static member of a class or interface.

604             every<S extends string | boolean>(predicate: (value: string | boolean, index: number, array: (string | boolean)[]) => value is S, thisArg?: any): this is S[];
                                                                                                                                                                  ~~~~


Found 1 error in node_modules/@ensdomains/ensjs/dist/types/index.d.ts:604
```

while using in a typescript project

**Comment by caliburn886** [comment]
> ```
> node_modules/@ensdomains/ensjs/dist/types/index.d.ts:604:159 - error TS2526: A 'this' type is available only in a non-static member of a class or interface.
> 
> 604             every<S extends string | boolean>(predicate: (value: string | boolean, index: number, array: (string | boolean)[]) => value is S, thisArg?: any): this is S[];
>                                                                                                                                                                   ~~~~
> 
> 
> Found 1 error in node_modules/@ensdomains/ensjs/dist/types/index.d.ts:604
> ```
> 
> while using in a typescript project

**Comment by sherpya** [comment]
> 

?

**Comment by TateB** [comment]
add `skipLibCheck: true` to your tsconfig to fix this
