### ISSUE TITLE
bug: getName not resolving correct for some addresses

### ISSUE THREAD

**Issue by alvaroraminelli** [ensdomains/ensjs-v3#168]
### Package Version

3.2.0

### Current Behavior

The getName function correctly resolves addresses for some ENS names (e.g., renanmav.eth and graynewfield.eth) and fails for others (e.g. alvaroraminelli.eth)

### Expected Behavior

getName for the following names:

renanmav.eth 
alvaroraminelli.eth
graynewfield.eth

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-uwm8cj?file=package.json,index.ts

**Comment by TateB** [comment]
already discussed in https://github.com/wevm/viem/issues/1753
