### ISSUE TITLE
Universal Resolver/coinType updates

### ISSUE THREAD

**Issue by technicallykind** [ensdomains/ensjs-v3#174]
Hi @TateB!

We deployed an example with your library https://github.com/TickerDao/tkn-js-example

We have two requirements:
1. Support hybird resolvers:
https://github.com/ensdomains/ens-contracts/pull/324
2. Support arbitrary coinTypes. We support many EVM chains that most likely won't be given 'BTC', 'SOL' style address-encoder keys.
https://github.com/ensdomains/address-encoder/pull/398

I'm posting here to track when these two dependency updates get updated here into ensjs. It looks like hopefully the dev work has already been completed on these two.

Thank you for your great work!

cc: @adraffy

**Comment by TateB** [comment]
released in v3.4.4
