### ISSUE TITLE
Deno Runtime: Buffer is not defined

### ISSUE THREAD

**Issue by 7flash** [ensdomains/ensjs-v3#40]
Unhandled exception: Error: Promise rejected without a handler: ReferenceError: Buffer is not defined

**Comment by 7flash** [comment]
![image](https://user-images.githubusercontent.com/4569866/186862824-39f6ac2b-f7f4-4474-9bfe-1e3c8d8e4e31.png)

**Comment by TateB** [comment]
can you run it with node compatibility mode enabled?
