### ISSUE TITLE
Cannot find module '../@types/FuseOptions' or its corresponding type declarations.

### ISSUE THREAD

**Issue by kliyer-ai** [ensdomains/ensjs-v3#51]
![image](https://user-images.githubusercontent.com/27199575/191228113-39c28041-f132-4b61-b8d5-4e83b1ed40dd.png)

This is my tsconfig:
```json
{
  "compilerOptions": {
    "rootDir": "./src/",
    "outDir": "./dist/",
    "target": "ES6",
    "lib": ["ES6"],
    "esModuleInterop": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "removeComments": true,
    "sourceMap": true,
    "strict": true
  },
  "include": ["./src/**/*"]
}
```

**Comment by kliyer-ai** [comment]
Okay I just saw that this should have been fixed in #49 but somehow it still breaks for me. Is something wrong with my tsconfing?

**Comment by kliyer-ai** [comment]
Hey @TateB, could you maybe help me with this? :)

**Comment by TateB** [comment]
are you still running into this issue?
