### ISSUE TITLE
`getProfile` does not update at the same time of `getOwner`

### ISSUE THREAD

**Issue by Magofoco** [ensdomains/ensjs-v3#96]
Let's assume I want to register this free ENS domain `myensname.eth`.
In my application I check in every block if `myensname.eth` has been registered via polling.
Inside my app, I call the functions `.getProfile` and `.getOwner`.

```js
  const provider = new ethers.providers.JsonRpcProvider(INFURA_NODE);
  await ENSInstance.setProvider(provider);

  provider.on("block", async () => {
    const ensProfileObject = await ENSInstance.getProfile(
      "myensname.eth"
    );

    const ensRegisteredObject = await ENSInstance.getOwner(
      "myensname.eth"
    );
    
    console.log(ensProfileObject)
    console.log(ensRegisteredObject)

}
```

Before registration, I have two `undefined` as output of the console.log
```js
    ensProfileObject: undefined
    ensRegisteredObject: undefined
```
then I register the ENS on https://app.ens.domains/
After the registration I get this:
```js
    ensProfileObject: undefined
    ensRegisteredObject: {
          registrant: '0x...402',
          owner: '0x...402',
          ownershipLevel: 'registrar'
        }

``` 

**Expected:**
Both `.getProfile` and `.getOwner` should return an object with the actual information
**Actual:**
Only `.getOwner` returns the object, `.getProfile` returns undefined

**Comment by TateB** [comment]
the subgraph needs to be up to date with the block in which the registration is done, nothing we can really do about the lag at the moment (although we are looking into it)
